apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 130575395405.dkr.ecr.us-east-1.amazonaws.com/repo-542378966167-result:85
        name: result
        ports:
        - containerPort: 80
          name: result
